/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssignmentStatus = { 'inTraining' : null } |
  { 'certified' : null };
export interface Category {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'positionId' : bigint,
  'coverPhoto' : [] | [string],
}
export interface Cell { 'value' : Value, 'name' : string }
export interface DetailField { 'value' : string, 'fieldLabel' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface LibraryItem {
  'id' : bigint,
  'categoryId' : bigint,
  'title' : string,
  'sortOrder' : bigint,
  'tags' : Array<string>,
  'seasonal' : boolean,
  'notes' : [] | [string],
  'details' : Array<DetailField>,
  'photo' : [] | [string],
  'subtitle' : [] | [string],
}
export interface NsoImportInput {
  'moduleName' : string,
  'phases' : Array<NsoImportPhase>,
}
export interface NsoImportPhase {
  'tasks' : Array<NsoImportTask>,
  'name' : string,
}
export interface NsoImportSummary {
  'phasesCreated' : bigint,
  'phasesReused' : bigint,
  'tasksAdded' : bigint,
}
export interface NsoImportTask {
  'text' : string,
  'section' : [] | [string],
  'notes' : [] | [string],
}
export interface Phase { 'id' : bigint, 'sortOrder' : bigint, 'name' : string }
export interface Position {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'description' : [] | [string],
  'coverPhoto' : [] | [string],
}
export interface PositionAssignment {
  'status' : AssignmentStatus,
  'userId' : Principal,
  'positionId' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'manager' : null } |
  { 'admin' : null } |
  { 'trainee' : null } |
  { 'trainer' : null };
export interface Task {
  'id' : bigint,
  'completionDate' : [] | [string],
  'assignedTo' : [] | [Principal],
  'sortOrder' : bigint,
  'done' : boolean,
  'text' : string,
  'section' : [] | [string],
  'notes' : [] | [string],
  'phaseId' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'role' : Role,
  'storeLocation' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__assignments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<PositionAssignment>
  >,
  '__categories' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Category>>,
  '__items' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<LibraryItem>>,
  '__nextCategoryId' : ActorMethod<[], any>,
  '__nextItemId' : ActorMethod<[], any>,
  '__nextPhaseId' : ActorMethod<[], any>,
  '__nextPositionId' : ActorMethod<[], any>,
  '__nextTaskId' : ActorMethod<[], any>,
  '__nsoPhases' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Phase>>,
  '__nsoTasks' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Task>>,
  '__positions' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Position>>,
  '__profiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPosition' : ActorMethod<[Principal, bigint], PositionAssignment>,
  'createCategory' : ActorMethod<[bigint, string, [] | [string]], Category>,
  'createItem' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      [] | [string],
      Array<DetailField>,
      [] | [string],
      Array<string>,
      boolean,
    ],
    LibraryItem
  >,
  'createMyProfile' : ActorMethod<[string, string], UserProfile>,
  'createNsoPhase' : ActorMethod<[string], Phase>,
  'createNsoTask' : ActorMethod<
    [bigint, string, [] | [string], [] | [Principal]],
    Task
  >,
  'createPosition' : ActorMethod<
    [string, [] | [string], [] | [string]],
    Position
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'deleteNsoPhase' : ActorMethod<[bigint], undefined>,
  'deleteNsoTask' : ActorMethod<[bigint], undefined>,
  'deletePosition' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getAllPositions' : ActorMethod<[], Array<Position>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoriesByPosition' : ActorMethod<[bigint], Array<Category>>,
  'getCategory' : ActorMethod<[bigint], [] | [Category]>,
  'getItem' : ActorMethod<[bigint], [] | [LibraryItem]>,
  'getItemsByCategory' : ActorMethod<[bigint], Array<LibraryItem>>,
  'getMyAssignments' : ActorMethod<[], Array<PositionAssignment>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getNsoAssignableUsers' : ActorMethod<[], Array<UserProfile>>,
  'getNsoOverallProgress' : ActorMethod<
    [],
    { 'doneCount' : bigint, 'totalCount' : bigint }
  >,
  'getNsoPhase' : ActorMethod<[bigint], [] | [Phase]>,
  'getNsoPhases' : ActorMethod<[], Array<Phase>>,
  'getNsoTask' : ActorMethod<[bigint], [] | [Task]>,
  'getNsoTasksByPhase' : ActorMethod<[bigint], Array<Task>>,
  'getPosition' : ActorMethod<[bigint], [] | [Position]>,
  'getUserAssignments' : ActorMethod<[Principal], Array<PositionAssignment>>,
  'getUserRole' : ActorMethod<[Principal], [] | [Role]>,
  'importNsoTasks' : ActorMethod<[NsoImportInput], NsoImportSummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderCategories' : ActorMethod<[bigint, Array<bigint>], Array<Category>>,
  'reorderItems' : ActorMethod<[bigint, Array<bigint>], Array<LibraryItem>>,
  'reorderNsoPhases' : ActorMethod<
    [bigint, { 'up' : null } | { 'down' : null }],
    undefined
  >,
  'reorderNsoTasks' : ActorMethod<
    [bigint, { 'up' : null } | { 'down' : null }],
    undefined
  >,
  'reorderPositions' : ActorMethod<[Array<bigint>], Array<Position>>,
  'schema' : ActorMethod<[], string>,
  'searchLibrary' : ActorMethod<[bigint, string], Array<LibraryItem>>,
  'setAssignmentStatus' : ActorMethod<
    [Principal, bigint, AssignmentStatus],
    PositionAssignment
  >,
  'setNsoTaskAssignment' : ActorMethod<[bigint, [] | [Principal]], undefined>,
  'setNsoTaskCompletionDate' : ActorMethod<[bigint, [] | [string]], undefined>,
  'setUserRole' : ActorMethod<[Principal, Role], UserProfile>,
  'toggleNsoTask' : ActorMethod<[bigint, boolean, [] | [string]], undefined>,
  'unassignPosition' : ActorMethod<[Principal, bigint], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, [] | [string]], Category>,
  'updateItem' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      [] | [string],
      Array<DetailField>,
      [] | [string],
      Array<string>,
      boolean,
    ],
    LibraryItem
  >,
  'updateMyProfile' : ActorMethod<[string, string], UserProfile>,
  'updateNsoPhase' : ActorMethod<[bigint, string], undefined>,
  'updateNsoTask' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      boolean,
      [] | [Principal],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updatePosition' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    Position
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];