/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssignmentStatus = IDL.Variant({
  'inTraining' : IDL.Null,
  'certified' : IDL.Null,
});
export const PositionAssignment = IDL.Record({
  'status' : AssignmentStatus,
  'userId' : IDL.Principal,
  'positionId' : IDL.Nat,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'positionId' : IDL.Nat,
  'coverPhoto' : IDL.Opt(IDL.Text),
});
export const DetailField = IDL.Record({
  'value' : IDL.Text,
  'fieldLabel' : IDL.Text,
});
export const LibraryItem = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'seasonal' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'details' : IDL.Vec(DetailField),
  'photo' : IDL.Opt(IDL.Text),
  'subtitle' : IDL.Opt(IDL.Text),
});
export const Position = IDL.Record({
  'id' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'coverPhoto' : IDL.Opt(IDL.Text),
});
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'trainee' : IDL.Null,
  'trainer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : Role,
  'storeLocation' : IDL.Text,
});
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__assignments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(PositionAssignment)],
      ['query'],
    ),
  '__categories' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Category)],
      ['query'],
    ),
  '__items' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(LibraryItem)],
      ['query'],
    ),
  '__nextCategoryId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextItemId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextPositionId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__positions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Position)],
      ['query'],
    ),
  '__profiles' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPosition' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [PositionAssignment],
      [],
    ),
  'createCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [Category],
      [],
    ),
  'createItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(DetailField),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [LibraryItem],
      [],
    ),
  'createMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'createPosition' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Position],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deletePosition' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoriesByPosition' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Category)],
      ['query'],
    ),
  'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(LibraryItem)], ['query']),
  'getItemsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(LibraryItem)], ['query']),
  'getMyAssignments' : IDL.Func([], [IDL.Vec(PositionAssignment)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getPosition' : IDL.Func([IDL.Nat], [IDL.Opt(Position)], ['query']),
  'getUserAssignments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PositionAssignment)],
      [],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(Role)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderCategories' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Vec(Category)],
      [],
    ),
  'reorderItems' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Vec(LibraryItem)],
      [],
    ),
  'reorderPositions' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Position)], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchLibrary' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(LibraryItem)],
      ['query'],
    ),
  'setAssignmentStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat, AssignmentStatus],
      [PositionAssignment],
      [],
    ),
  'setUserRole' : IDL.Func([IDL.Principal, Role], [UserProfile], []),
  'unassignPosition' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [Category],
      [],
    ),
  'updateItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(DetailField),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [LibraryItem],
      [],
    ),
  'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'updatePosition' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Position],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssignmentStatus = IDL.Variant({
    'inTraining' : IDL.Null,
    'certified' : IDL.Null,
  });
  const PositionAssignment = IDL.Record({
    'status' : AssignmentStatus,
    'userId' : IDL.Principal,
    'positionId' : IDL.Nat,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'positionId' : IDL.Nat,
    'coverPhoto' : IDL.Opt(IDL.Text),
  });
  const DetailField = IDL.Record({
    'value' : IDL.Text,
    'fieldLabel' : IDL.Text,
  });
  const LibraryItem = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'seasonal' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'details' : IDL.Vec(DetailField),
    'photo' : IDL.Opt(IDL.Text),
    'subtitle' : IDL.Opt(IDL.Text),
  });
  const Position = IDL.Record({
    'id' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'coverPhoto' : IDL.Opt(IDL.Text),
  });
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'trainee' : IDL.Null,
    'trainer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : Role,
    'storeLocation' : IDL.Text,
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__assignments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(PositionAssignment)],
        ['query'],
      ),
    '__categories' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Category)],
        ['query'],
      ),
    '__items' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    '__nextCategoryId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextItemId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextPositionId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__positions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Position)],
        ['query'],
      ),
    '__profiles' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPosition' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [PositionAssignment],
        [],
      ),
    'createCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [Category],
        [],
      ),
    'createItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(DetailField),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [LibraryItem],
        [],
      ),
    'createMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'createPosition' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Position],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deletePosition' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoriesByPosition' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Category)],
        ['query'],
      ),
    'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
    'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(LibraryItem)], ['query']),
    'getItemsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    'getMyAssignments' : IDL.Func([], [IDL.Vec(PositionAssignment)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getPosition' : IDL.Func([IDL.Nat], [IDL.Opt(Position)], ['query']),
    'getUserAssignments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PositionAssignment)],
        [],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(Role)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderCategories' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Vec(Category)],
        [],
      ),
    'reorderItems' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Vec(LibraryItem)],
        [],
      ),
    'reorderPositions' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Position)], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchLibrary' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    'setAssignmentStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, AssignmentStatus],
        [PositionAssignment],
        [],
      ),
    'setUserRole' : IDL.Func([IDL.Principal, Role], [UserProfile], []),
    'unassignPosition' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [Category],
        [],
      ),
    'updateItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(DetailField),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [LibraryItem],
        [],
      ),
    'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'updatePosition' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Position],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };