/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssignmentStatus = IDL.Variant({
  'inTraining' : IDL.Null,
  'certified' : IDL.Null,
});
export const PositionAssignment = IDL.Record({
  'status' : AssignmentStatus,
  'userId' : IDL.Principal,
  'positionId' : IDL.Nat,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'accentColor' : IDL.Opt(IDL.Text),
  'positionId' : IDL.Nat,
  'coverPhoto' : IDL.Opt(IDL.Text),
});
export const FoodServiceware = IDL.Record({
  'item' : IDL.Text,
  'amount' : IDL.Text,
});
export const FoodRecipeKind = IDL.Variant({
  'prep' : IDL.Null,
  'menuBuild' : IDL.Null,
});
export const FoodComponentSize = IDL.Record({
  'value' : IDL.Text,
  'size' : IDL.Text,
});
export const FoodComponent = IDL.Record({
  'anchorY' : IDL.Opt(IDL.Float64),
  'item' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'amounts' : IDL.Vec(FoodComponentSize),
  'group' : IDL.Opt(IDL.Text),
  'amount' : IDL.Text,
});
export const FoodRecipe = IDL.Record({
  'lineUtensil' : IDL.Opt(IDL.Text),
  'serviceware' : IDL.Vec(FoodServiceware),
  'station' : IDL.Text,
  'equipment' : IDL.Opt(IDL.Text),
  'holdTemp' : IDL.Opt(IDL.Text),
  'kind' : FoodRecipeKind,
  'buildHeader' : IDL.Opt(IDL.Text),
  'qualityIdentifiers' : IDL.Vec(IDL.Text),
  'components' : IDL.Vec(FoodComponent),
  'shelfLife' : IDL.Opt(IDL.Text),
  'steps' : IDL.Vec(IDL.Text),
  'yieldText' : IDL.Opt(IDL.Text),
  'storeTemp' : IDL.Opt(IDL.Text),
  'menuSection' : IDL.Opt(IDL.Text),
  'expoSteps' : IDL.Vec(IDL.Text),
  'allergenNote' : IDL.Opt(IDL.Text),
});
export const DetailField = IDL.Record({
  'value' : IDL.Text,
  'fieldLabel' : IDL.Text,
});
export const RecipeSpec = IDL.Record({
  'ingredient' : IDL.Text,
  'upsell' : IDL.Bool,
  'amount' : IDL.Text,
});
export const RecipeVariant = IDL.Record({
  'variantLabel' : IDL.Text,
  'specs' : IDL.Vec(RecipeSpec),
  'assembly' : IDL.Vec(IDL.Text),
});
export const Recipe = IDL.Record({
  'equipment' : IDL.Vec(IDL.Text),
  'recapAudio' : IDL.Opt(IDL.Text),
  'glassware' : IDL.Text,
  'variants' : IDL.Vec(RecipeVariant),
  'garnish' : IDL.Vec(IDL.Text),
  'qualityIdentifier' : IDL.Vec(IDL.Text),
  'specs' : IDL.Vec(RecipeSpec),
  'shelfLife' : IDL.Opt(IDL.Text),
  'buildAudio' : IDL.Opt(IDL.Text),
  'assembly' : IDL.Vec(IDL.Text),
  'yield' : IDL.Opt(IDL.Text),
});
export const LibraryItem = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'foodRecipe' : IDL.Opt(FoodRecipe),
  'seasonal' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'details' : IDL.Vec(DetailField),
  'photo' : IDL.Opt(IDL.Text),
  'subtitle' : IDL.Opt(IDL.Text),
  'recipe' : IDL.Opt(Recipe),
});
export const ActivityType = IDL.Variant({
  'drinksBuilder' : IDL.Null,
  'quiz' : IDL.Null,
  'flashcards' : IDL.Null,
});
export const DrinksBuilderPrompt = IDL.Record({
  'text' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
});
export const DrinksBuilderAnswerClip = IDL.Record({
  'audioUrl' : IDL.Text,
  'answer' : IDL.Text,
});
export const DrinksBuilderSettings = IDL.Record({
  'garnishPrompts' : IDL.Vec(DrinksBuilderPrompt),
  'includedCategories' : IDL.Vec(IDL.Text),
  'enforceAssemblyOrder' : IDL.Bool,
  'pointsPerCorrect' : IDL.Nat,
  'excludedDrinkTitles' : IDL.Vec(IDL.Text),
  'showScoring' : IDL.Bool,
  'assemblyPrompts' : IDL.Vec(DrinksBuilderPrompt),
  'requireExactAmounts' : IDL.Bool,
  'answerClips' : IDL.Vec(DrinksBuilderAnswerClip),
  'glasswarePrompts' : IDL.Vec(DrinksBuilderPrompt),
  'soundDefault' : IDL.Bool,
  'decoyCount' : IDL.Nat,
  'celebrationClips' : IDL.Vec(IDL.Text),
  'correctAffirmations' : IDL.Vec(IDL.Text),
  'specsPrompts' : IDL.Vec(DrinksBuilderPrompt),
  'streakMultiplier' : IDL.Bool,
  'roundsPerSession' : IDL.Nat,
});
export const DrinksBuilderContent = IDL.Record({
  'settings' : DrinksBuilderSettings,
});
export const Question = IDL.Variant({
  'multipleChoice' : IDL.Record({
    'correctIndex' : IDL.Nat,
    'prompt' : IDL.Text,
    'choices' : IDL.Vec(IDL.Text),
  }),
  'matching' : IDL.Record({
    'pairs' : IDL.Vec(
      IDL.Record({ 'itemTitle' : IDL.Text, 'fieldValue' : IDL.Text })
    ),
    'shuffledOptions' : IDL.Vec(IDL.Text),
  }),
  'trueFalse' : IDL.Record({ 'statement' : IDL.Text, 'isTrue' : IDL.Bool }),
});
export const QuizContent = IDL.Vec(Question);
export const FlashcardRecipe = IDL.Record({
  'glassware' : IDL.Text,
  'garnish' : IDL.Vec(IDL.Text),
  'specs' : IDL.Vec(
    IDL.Record({ 'ingredient' : IDL.Text, 'amount' : IDL.Text })
  ),
  'assembly' : IDL.Vec(IDL.Text),
});
export const Flashcard = IDL.Record({
  'itemTitle' : IDL.Text,
  'detailFields' : IDL.Vec(
    IDL.Record({ 'value' : IDL.Text, 'fieldLabel' : IDL.Text })
  ),
  'itemPhoto' : IDL.Opt(IDL.Text),
  'recipe' : IDL.Opt(FlashcardRecipe),
});
export const FlashcardContent = IDL.Vec(Flashcard);
export const ActivityContent = IDL.Variant({
  'drinksBuilderContent' : DrinksBuilderContent,
  'quizContent' : QuizContent,
  'flashcardContent' : FlashcardContent,
});
export const QuizSettings = IDL.Record({
  'includeTrueFalse' : IDL.Bool,
  'includeMatching' : IDL.Bool,
  'includeMultipleChoice' : IDL.Bool,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : ActivityType,
  'content' : ActivityContent,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'createdBy' : IDL.Principal,
  'positionId' : IDL.Nat,
  'sourceCategoryIds' : IDL.Vec(IDL.Nat),
  'quizSettings' : IDL.Opt(QuizSettings),
});
export const Phase = IDL.Record({
  'id' : IDL.Nat,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'completionDate' : IDL.Opt(IDL.Text),
  'assignedTo' : IDL.Opt(IDL.Principal),
  'sortOrder' : IDL.Nat,
  'done' : IDL.Bool,
  'text' : IDL.Text,
  'section' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'phaseId' : IDL.Nat,
});
export const LayoutStyle = IDL.Variant({
  'library' : IDL.Null,
  'kitchen' : IDL.Null,
  'orientation' : IDL.Null,
});
export const Position = IDL.Record({
  'id' : IDL.Nat,
  'layoutStyle' : LayoutStyle,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'coverPhoto' : IDL.Opt(IDL.Text),
});
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'trainee' : IDL.Null,
  'trainer' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Opt(IDL.Text),
  'approvalStatus' : ApprovalStatus,
  'storeLocation' : IDL.Text,
  'photo' : IDL.Opt(IDL.Text),
});
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BuildActivityInput = IDL.Record({
  'activityType' : ActivityType,
  'content' : IDL.Opt(ActivityContent),
  'name' : IDL.Text,
  'positionId' : IDL.Nat,
  'sourceCategoryIds' : IDL.Vec(IDL.Nat),
  'quizSettings' : IDL.Opt(QuizSettings),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const NsoPhaseProgressCount = IDL.Record({
  'doneCount' : IDL.Nat,
  'totalCount' : IDL.Nat,
  'phaseId' : IDL.Nat,
});
export const NsoImportTask = IDL.Record({
  'text' : IDL.Text,
  'section' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
});
export const NsoImportPhase = IDL.Record({
  'tasks' : IDL.Vec(NsoImportTask),
  'name' : IDL.Text,
});
export const NsoImportInput = IDL.Record({
  'moduleName' : IDL.Text,
  'phases' : IDL.Vec(NsoImportPhase),
});
export const NsoImportSummary = IDL.Record({
  'phasesCreated' : IDL.Nat,
  'phasesReused' : IDL.Nat,
  'tasksAdded' : IDL.Nat,
});
export const SendResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UpdateActivityInput = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Opt(ActivityContent),
  'name' : IDL.Text,
  'sourceCategoryIds' : IDL.Vec(IDL.Nat),
  'quizSettings' : IDL.Opt(QuizSettings),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__assignments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(PositionAssignment)],
      ['query'],
    ),
  '__categories' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Category)],
      ['query'],
    ),
  '__items' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(LibraryItem)],
      ['query'],
    ),
  '__legendaryActivities' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  '__nextCategoryId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextItemId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextLegendaryActivityId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextPhaseId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextPositionId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextTaskId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nsoPhases' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Phase)],
      ['query'],
    ),
  '__nsoTasks' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Task)],
      ['query'],
    ),
  '__positions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Position)],
      ['query'],
    ),
  '__profiles' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  '__verifiedEmails' : IDL.Func([], [IDL.Reserved], ['query']),
  '_caffeineEmailVerify' : IDL.Func([IDL.Text], [], []),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'approveUser' : IDL.Func([IDL.Principal], [UserProfile], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPosition' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [PositionAssignment],
      [],
    ),
  'buildLegendaryActivity' : IDL.Func([BuildActivityInput], [Activity], []),
  'createCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Category],
      [],
    ),
  'createItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(DetailField),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Opt(Recipe),
        IDL.Opt(FoodRecipe),
      ],
      [LibraryItem],
      [],
    ),
  'createMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'createNsoPhase' : IDL.Func([IDL.Text], [Phase], []),
  'createNsoTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Principal)],
      [Task],
      [],
    ),
  'createPosition' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), LayoutStyle],
      [Position],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deleteLegendaryActivity' : IDL.Func([IDL.Nat], [], []),
  'deleteNsoPhase' : IDL.Func([IDL.Nat], [], []),
  'deleteNsoTask' : IDL.Func([IDL.Nat], [], []),
  'deletePosition' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoriesByPosition' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Category)],
      ['query'],
    ),
  'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
  'getDrinksBuilderDecoyPool' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LibraryItem)],
      ['query'],
    ),
  'getDrinksBuilderPlayablePool' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LibraryItem)],
      ['query'],
    ),
  'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(LibraryItem)], ['query']),
  'getItemsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(LibraryItem)], ['query']),
  'getLegendaryActivitiesByPosition' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getLegendaryActivity' : IDL.Func([IDL.Nat], [IDL.Opt(Activity)], ['query']),
  'getMyAssignments' : IDL.Func([], [IDL.Vec(PositionAssignment)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getNsoAssignableUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getNsoOverallProgress' : IDL.Func(
      [],
      [IDL.Record({ 'doneCount' : IDL.Nat, 'totalCount' : IDL.Nat })],
      ['query'],
    ),
  'getNsoPhase' : IDL.Func([IDL.Nat], [IDL.Opt(Phase)], ['query']),
  'getNsoPhaseProgressCounts' : IDL.Func(
      [],
      [IDL.Vec(NsoPhaseProgressCount)],
      ['query'],
    ),
  'getNsoPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
  'getNsoTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getNsoTasksByPhase' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getPosition' : IDL.Func([IDL.Nat], [IDL.Opt(Position)], ['query']),
  'getUserAssignments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PositionAssignment)],
      [],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(Role)], []),
  'importNsoTasks' : IDL.Func([NsoImportInput], [NsoImportSummary], []),
  'initiateEmailVerification' : IDL.Func([IDL.Text], [SendResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rebuildLegendaryActivity' : IDL.Func([IDL.Nat], [Activity], []),
  'rejectUser' : IDL.Func([IDL.Principal], [UserProfile], []),
  'reorderCategories' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Vec(Category)],
      [],
    ),
  'reorderItems' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Vec(LibraryItem)],
      [],
    ),
  'reorderNsoPhases' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'up' : IDL.Null, 'down' : IDL.Null })],
      [],
      [],
    ),
  'reorderNsoTasks' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'up' : IDL.Null, 'down' : IDL.Null })],
      [],
      [],
    ),
  'reorderPositions' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Position)], []),
  'resendApprovalEmail' : IDL.Func([IDL.Principal], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchLibrary' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(LibraryItem)],
      ['query'],
    ),
  'setAssignmentStatus' : IDL.Func(
      [IDL.Principal, IDL.Nat, AssignmentStatus],
      [PositionAssignment],
      [],
    ),
  'setEmailForUser' : IDL.Func([IDL.Text], [UserProfile], []),
  'setMyPhoto' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
  'setNsoTaskAssignment' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Principal)], [], []),
  'setNsoTaskCompletionDate' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'setUserEmail' : IDL.Func([IDL.Principal, IDL.Text], [UserProfile], []),
  'setUserPhoto' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Text)],
      [UserProfile],
      [],
    ),
  'setUserRole' : IDL.Func([IDL.Principal, Role], [UserProfile], []),
  'toggleNsoTask' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)], [], []),
  'unassignPosition' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Category],
      [],
    ),
  'updateItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(DetailField),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Opt(Recipe),
        IDL.Opt(FoodRecipe),
      ],
      [LibraryItem],
      [],
    ),
  'updateLegendaryActivity' : IDL.Func([UpdateActivityInput], [Activity], []),
  'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'updateMyProfileWithPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [UserProfile],
      [],
    ),
  'updateNsoPhase' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateNsoTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updatePosition' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), LayoutStyle],
      [Position],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssignmentStatus = IDL.Variant({
    'inTraining' : IDL.Null,
    'certified' : IDL.Null,
  });
  const PositionAssignment = IDL.Record({
    'status' : AssignmentStatus,
    'userId' : IDL.Principal,
    'positionId' : IDL.Nat,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'accentColor' : IDL.Opt(IDL.Text),
    'positionId' : IDL.Nat,
    'coverPhoto' : IDL.Opt(IDL.Text),
  });
  const FoodServiceware = IDL.Record({
    'item' : IDL.Text,
    'amount' : IDL.Text,
  });
  const FoodRecipeKind = IDL.Variant({
    'prep' : IDL.Null,
    'menuBuild' : IDL.Null,
  });
  const FoodComponentSize = IDL.Record({
    'value' : IDL.Text,
    'size' : IDL.Text,
  });
  const FoodComponent = IDL.Record({
    'anchorY' : IDL.Opt(IDL.Float64),
    'item' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'amounts' : IDL.Vec(FoodComponentSize),
    'group' : IDL.Opt(IDL.Text),
    'amount' : IDL.Text,
  });
  const FoodRecipe = IDL.Record({
    'lineUtensil' : IDL.Opt(IDL.Text),
    'serviceware' : IDL.Vec(FoodServiceware),
    'station' : IDL.Text,
    'equipment' : IDL.Opt(IDL.Text),
    'holdTemp' : IDL.Opt(IDL.Text),
    'kind' : FoodRecipeKind,
    'buildHeader' : IDL.Opt(IDL.Text),
    'qualityIdentifiers' : IDL.Vec(IDL.Text),
    'components' : IDL.Vec(FoodComponent),
    'shelfLife' : IDL.Opt(IDL.Text),
    'steps' : IDL.Vec(IDL.Text),
    'yieldText' : IDL.Opt(IDL.Text),
    'storeTemp' : IDL.Opt(IDL.Text),
    'menuSection' : IDL.Opt(IDL.Text),
    'expoSteps' : IDL.Vec(IDL.Text),
    'allergenNote' : IDL.Opt(IDL.Text),
  });
  const DetailField = IDL.Record({
    'value' : IDL.Text,
    'fieldLabel' : IDL.Text,
  });
  const RecipeSpec = IDL.Record({
    'ingredient' : IDL.Text,
    'upsell' : IDL.Bool,
    'amount' : IDL.Text,
  });
  const RecipeVariant = IDL.Record({
    'variantLabel' : IDL.Text,
    'specs' : IDL.Vec(RecipeSpec),
    'assembly' : IDL.Vec(IDL.Text),
  });
  const Recipe = IDL.Record({
    'equipment' : IDL.Vec(IDL.Text),
    'recapAudio' : IDL.Opt(IDL.Text),
    'glassware' : IDL.Text,
    'variants' : IDL.Vec(RecipeVariant),
    'garnish' : IDL.Vec(IDL.Text),
    'qualityIdentifier' : IDL.Vec(IDL.Text),
    'specs' : IDL.Vec(RecipeSpec),
    'shelfLife' : IDL.Opt(IDL.Text),
    'buildAudio' : IDL.Opt(IDL.Text),
    'assembly' : IDL.Vec(IDL.Text),
    'yield' : IDL.Opt(IDL.Text),
  });
  const LibraryItem = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'foodRecipe' : IDL.Opt(FoodRecipe),
    'seasonal' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'details' : IDL.Vec(DetailField),
    'photo' : IDL.Opt(IDL.Text),
    'subtitle' : IDL.Opt(IDL.Text),
    'recipe' : IDL.Opt(Recipe),
  });
  const ActivityType = IDL.Variant({
    'drinksBuilder' : IDL.Null,
    'quiz' : IDL.Null,
    'flashcards' : IDL.Null,
  });
  const DrinksBuilderPrompt = IDL.Record({
    'text' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
  });
  const DrinksBuilderAnswerClip = IDL.Record({
    'audioUrl' : IDL.Text,
    'answer' : IDL.Text,
  });
  const DrinksBuilderSettings = IDL.Record({
    'garnishPrompts' : IDL.Vec(DrinksBuilderPrompt),
    'includedCategories' : IDL.Vec(IDL.Text),
    'enforceAssemblyOrder' : IDL.Bool,
    'pointsPerCorrect' : IDL.Nat,
    'excludedDrinkTitles' : IDL.Vec(IDL.Text),
    'showScoring' : IDL.Bool,
    'assemblyPrompts' : IDL.Vec(DrinksBuilderPrompt),
    'requireExactAmounts' : IDL.Bool,
    'answerClips' : IDL.Vec(DrinksBuilderAnswerClip),
    'glasswarePrompts' : IDL.Vec(DrinksBuilderPrompt),
    'soundDefault' : IDL.Bool,
    'decoyCount' : IDL.Nat,
    'celebrationClips' : IDL.Vec(IDL.Text),
    'correctAffirmations' : IDL.Vec(IDL.Text),
    'specsPrompts' : IDL.Vec(DrinksBuilderPrompt),
    'streakMultiplier' : IDL.Bool,
    'roundsPerSession' : IDL.Nat,
  });
  const DrinksBuilderContent = IDL.Record({
    'settings' : DrinksBuilderSettings,
  });
  const Question = IDL.Variant({
    'multipleChoice' : IDL.Record({
      'correctIndex' : IDL.Nat,
      'prompt' : IDL.Text,
      'choices' : IDL.Vec(IDL.Text),
    }),
    'matching' : IDL.Record({
      'pairs' : IDL.Vec(
        IDL.Record({ 'itemTitle' : IDL.Text, 'fieldValue' : IDL.Text })
      ),
      'shuffledOptions' : IDL.Vec(IDL.Text),
    }),
    'trueFalse' : IDL.Record({ 'statement' : IDL.Text, 'isTrue' : IDL.Bool }),
  });
  const QuizContent = IDL.Vec(Question);
  const FlashcardRecipe = IDL.Record({
    'glassware' : IDL.Text,
    'garnish' : IDL.Vec(IDL.Text),
    'specs' : IDL.Vec(
      IDL.Record({ 'ingredient' : IDL.Text, 'amount' : IDL.Text })
    ),
    'assembly' : IDL.Vec(IDL.Text),
  });
  const Flashcard = IDL.Record({
    'itemTitle' : IDL.Text,
    'detailFields' : IDL.Vec(
      IDL.Record({ 'value' : IDL.Text, 'fieldLabel' : IDL.Text })
    ),
    'itemPhoto' : IDL.Opt(IDL.Text),
    'recipe' : IDL.Opt(FlashcardRecipe),
  });
  const FlashcardContent = IDL.Vec(Flashcard);
  const ActivityContent = IDL.Variant({
    'drinksBuilderContent' : DrinksBuilderContent,
    'quizContent' : QuizContent,
    'flashcardContent' : FlashcardContent,
  });
  const QuizSettings = IDL.Record({
    'includeTrueFalse' : IDL.Bool,
    'includeMatching' : IDL.Bool,
    'includeMultipleChoice' : IDL.Bool,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : ActivityType,
    'content' : ActivityContent,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'createdBy' : IDL.Principal,
    'positionId' : IDL.Nat,
    'sourceCategoryIds' : IDL.Vec(IDL.Nat),
    'quizSettings' : IDL.Opt(QuizSettings),
  });
  const Phase = IDL.Record({
    'id' : IDL.Nat,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'completionDate' : IDL.Opt(IDL.Text),
    'assignedTo' : IDL.Opt(IDL.Principal),
    'sortOrder' : IDL.Nat,
    'done' : IDL.Bool,
    'text' : IDL.Text,
    'section' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'phaseId' : IDL.Nat,
  });
  const LayoutStyle = IDL.Variant({
    'library' : IDL.Null,
    'kitchen' : IDL.Null,
    'orientation' : IDL.Null,
  });
  const Position = IDL.Record({
    'id' : IDL.Nat,
    'layoutStyle' : LayoutStyle,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'coverPhoto' : IDL.Opt(IDL.Text),
  });
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'trainee' : IDL.Null,
    'trainer' : IDL.Null,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Opt(IDL.Text),
    'approvalStatus' : ApprovalStatus,
    'storeLocation' : IDL.Text,
    'photo' : IDL.Opt(IDL.Text),
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BuildActivityInput = IDL.Record({
    'activityType' : ActivityType,
    'content' : IDL.Opt(ActivityContent),
    'name' : IDL.Text,
    'positionId' : IDL.Nat,
    'sourceCategoryIds' : IDL.Vec(IDL.Nat),
    'quizSettings' : IDL.Opt(QuizSettings),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const NsoPhaseProgressCount = IDL.Record({
    'doneCount' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'phaseId' : IDL.Nat,
  });
  const NsoImportTask = IDL.Record({
    'text' : IDL.Text,
    'section' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
  });
  const NsoImportPhase = IDL.Record({
    'tasks' : IDL.Vec(NsoImportTask),
    'name' : IDL.Text,
  });
  const NsoImportInput = IDL.Record({
    'moduleName' : IDL.Text,
    'phases' : IDL.Vec(NsoImportPhase),
  });
  const NsoImportSummary = IDL.Record({
    'phasesCreated' : IDL.Nat,
    'phasesReused' : IDL.Nat,
    'tasksAdded' : IDL.Nat,
  });
  const SendResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UpdateActivityInput = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Opt(ActivityContent),
    'name' : IDL.Text,
    'sourceCategoryIds' : IDL.Vec(IDL.Nat),
    'quizSettings' : IDL.Opt(QuizSettings),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__assignments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(PositionAssignment)],
        ['query'],
      ),
    '__categories' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Category)],
        ['query'],
      ),
    '__items' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    '__legendaryActivities' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    '__nextCategoryId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextItemId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextLegendaryActivityId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextPhaseId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextPositionId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextTaskId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nsoPhases' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Phase)],
        ['query'],
      ),
    '__nsoTasks' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Task)],
        ['query'],
      ),
    '__positions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Position)],
        ['query'],
      ),
    '__profiles' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    '__verifiedEmails' : IDL.Func([], [IDL.Reserved], ['query']),
    '_caffeineEmailVerify' : IDL.Func([IDL.Text], [], []),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'approveUser' : IDL.Func([IDL.Principal], [UserProfile], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPosition' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [PositionAssignment],
        [],
      ),
    'buildLegendaryActivity' : IDL.Func([BuildActivityInput], [Activity], []),
    'createCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Category],
        [],
      ),
    'createItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(DetailField),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Opt(Recipe),
          IDL.Opt(FoodRecipe),
        ],
        [LibraryItem],
        [],
      ),
    'createMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'createNsoPhase' : IDL.Func([IDL.Text], [Phase], []),
    'createNsoTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Principal)],
        [Task],
        [],
      ),
    'createPosition' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), LayoutStyle],
        [Position],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deleteLegendaryActivity' : IDL.Func([IDL.Nat], [], []),
    'deleteNsoPhase' : IDL.Func([IDL.Nat], [], []),
    'deleteNsoTask' : IDL.Func([IDL.Nat], [], []),
    'deletePosition' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoriesByPosition' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Category)],
        ['query'],
      ),
    'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
    'getDrinksBuilderDecoyPool' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    'getDrinksBuilderPlayablePool' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    'getItem' : IDL.Func([IDL.Nat], [IDL.Opt(LibraryItem)], ['query']),
    'getItemsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    'getLegendaryActivitiesByPosition' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getLegendaryActivity' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Activity)],
        ['query'],
      ),
    'getMyAssignments' : IDL.Func([], [IDL.Vec(PositionAssignment)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getNsoAssignableUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getNsoOverallProgress' : IDL.Func(
        [],
        [IDL.Record({ 'doneCount' : IDL.Nat, 'totalCount' : IDL.Nat })],
        ['query'],
      ),
    'getNsoPhase' : IDL.Func([IDL.Nat], [IDL.Opt(Phase)], ['query']),
    'getNsoPhaseProgressCounts' : IDL.Func(
        [],
        [IDL.Vec(NsoPhaseProgressCount)],
        ['query'],
      ),
    'getNsoPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
    'getNsoTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getNsoTasksByPhase' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getPosition' : IDL.Func([IDL.Nat], [IDL.Opt(Position)], ['query']),
    'getUserAssignments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PositionAssignment)],
        [],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(Role)], []),
    'importNsoTasks' : IDL.Func([NsoImportInput], [NsoImportSummary], []),
    'initiateEmailVerification' : IDL.Func([IDL.Text], [SendResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rebuildLegendaryActivity' : IDL.Func([IDL.Nat], [Activity], []),
    'rejectUser' : IDL.Func([IDL.Principal], [UserProfile], []),
    'reorderCategories' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Vec(Category)],
        [],
      ),
    'reorderItems' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Vec(LibraryItem)],
        [],
      ),
    'reorderNsoPhases' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'up' : IDL.Null, 'down' : IDL.Null })],
        [],
        [],
      ),
    'reorderNsoTasks' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'up' : IDL.Null, 'down' : IDL.Null })],
        [],
        [],
      ),
    'reorderPositions' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Position)], []),
    'resendApprovalEmail' : IDL.Func([IDL.Principal], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchLibrary' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(LibraryItem)],
        ['query'],
      ),
    'setAssignmentStatus' : IDL.Func(
        [IDL.Principal, IDL.Nat, AssignmentStatus],
        [PositionAssignment],
        [],
      ),
    'setEmailForUser' : IDL.Func([IDL.Text], [UserProfile], []),
    'setMyPhoto' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
    'setNsoTaskAssignment' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'setNsoTaskCompletionDate' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'setUserEmail' : IDL.Func([IDL.Principal, IDL.Text], [UserProfile], []),
    'setUserPhoto' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
    'setUserRole' : IDL.Func([IDL.Principal, Role], [UserProfile], []),
    'toggleNsoTask' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)], [], []),
    'unassignPosition' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Category],
        [],
      ),
    'updateItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(DetailField),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Opt(Recipe),
          IDL.Opt(FoodRecipe),
        ],
        [LibraryItem],
        [],
      ),
    'updateLegendaryActivity' : IDL.Func([UpdateActivityInput], [Activity], []),
    'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'updateMyProfileWithPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
    'updateNsoPhase' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateNsoTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updatePosition' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), LayoutStyle],
        [Position],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };