/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssignmentStatus = { 'inTraining' : null } |
  { 'certified' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Position {
  'id' : bigint,
  'sortOrder' : bigint,
  'name' : string,
  'description' : [] | [string],
  'coverPhoto' : [] | [string],
}
export interface PositionAssignment {
  'status' : AssignmentStatus,
  'userId' : Principal,
  'positionId' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'manager' : null } |
  { 'admin' : null } |
  { 'trainee' : null } |
  { 'trainer' : null };
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'role' : Role,
  'storeLocation' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__assignments' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<PositionAssignment>
  >,
  '__nextPositionId' : ActorMethod<[], any>,
  '__positions' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Position>>,
  '__profiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPosition' : ActorMethod<[Principal, bigint], PositionAssignment>,
  'createMyProfile' : ActorMethod<[string, string], UserProfile>,
  'createPosition' : ActorMethod<
    [string, [] | [string], [] | [string]],
    Position
  >,
  'deletePosition' : ActorMethod<[bigint], undefined>,
  'getAllPositions' : ActorMethod<[], Array<Position>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAssignments' : ActorMethod<[], Array<PositionAssignment>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPosition' : ActorMethod<[bigint], [] | [Position]>,
  'getUserAssignments' : ActorMethod<[Principal], Array<PositionAssignment>>,
  'getUserRole' : ActorMethod<[Principal], [] | [Role]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderPositions' : ActorMethod<[Array<bigint>], Array<Position>>,
  'setAssignmentStatus' : ActorMethod<
    [Principal, bigint, AssignmentStatus],
    PositionAssignment
  >,
  'setUserRole' : ActorMethod<[Principal, Role], UserProfile>,
  'unassignPosition' : ActorMethod<[Principal, bigint], undefined>,
  'updateMyProfile' : ActorMethod<[string, string], UserProfile>,
  'updatePosition' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    Position
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];