/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Task {
    id: bigint;
    completionDate?: string;
    assignedTo?: Principal;
    sortOrder: bigint;
    done: boolean;
    text: string;
    section?: string;
    notes?: string;
    phaseId: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface NsoImportInput {
    moduleName: string;
    phases: Array<NsoImportPhase>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Phase {
    id: bigint;
    sortOrder: bigint;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface DetailField {
    value: string;
    fieldLabel: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Position {
    id: bigint;
    sortOrder: bigint;
    name: string;
    description?: string;
    coverPhoto?: string;
}
export interface PositionAssignment {
    status: AssignmentStatus;
    userId: Principal;
    positionId: bigint;
}
export interface NsoImportTask {
    text: string;
    section?: string;
    notes?: string;
}
export interface NsoImportSummary {
    phasesCreated: bigint;
    phasesReused: bigint;
    tasksAdded: bigint;
}
export interface NsoImportPhase {
    tasks: Array<NsoImportTask>;
    name: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface LibraryItem {
    id: bigint;
    categoryId: bigint;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    seasonal: boolean;
    notes?: string;
    details: Array<DetailField>;
    photo?: string;
    subtitle?: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface NsoPhaseProgressCount {
    doneCount: bigint;
    totalCount: bigint;
    phaseId: bigint;
}
export interface UserProfile {
    id: Principal;
    name: string;
    role: Role;
    storeLocation: string;
}
export interface Category {
    id: bigint;
    sortOrder: bigint;
    name: string;
    positionId: bigint;
    coverPhoto?: string;
}
export enum AssignmentStatus {
    inTraining = "inTraining",
    certified = "certified"
}
export enum Role {
    manager = "manager",
    admin = "admin",
    trainee = "trainee",
    trainer = "trainer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_up_down {
    up = "up",
    down = "down"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __assignments(io: bigint | null, count: bigint | null): Promise<Array<PositionAssignment>>;
    __categories(io: bigint | null, count: bigint | null): Promise<Array<Category>>;
    __items(io: bigint | null, count: bigint | null): Promise<Array<LibraryItem>>;
    __nextCategoryId(): Promise<any>;
    __nextItemId(): Promise<any>;
    __nextPhaseId(): Promise<any>;
    __nextPositionId(): Promise<any>;
    __nextTaskId(): Promise<any>;
    __nsoPhases(io: bigint | null, count: bigint | null): Promise<Array<Phase>>;
    __nsoTasks(io: bigint | null, count: bigint | null): Promise<Array<Task>>;
    __positions(io: bigint | null, count: bigint | null): Promise<Array<Position>>;
    __profiles(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, UserProfile]>>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignPosition(userId: Principal, positionId: bigint): Promise<PositionAssignment>;
    createCategory(positionId: bigint, name: string, coverPhoto: string | null): Promise<Category>;
    createItem(categoryId: bigint, title: string, subtitle: string | null, photo: string | null, details: Array<DetailField>, notes: string | null, tags: Array<string>, seasonal: boolean): Promise<LibraryItem>;
    createMyProfile(name: string, storeLocation: string): Promise<UserProfile>;
    createNsoPhase(name: string): Promise<Phase>;
    createNsoTask(phaseId: bigint, text: string, section: string | null, assignedTo: Principal | null): Promise<Task>;
    createPosition(name: string, description: string | null, coverPhoto: string | null): Promise<Position>;
    deleteCategory(categoryId: bigint): Promise<void>;
    deleteItem(itemId: bigint): Promise<void>;
    deleteNsoPhase(id: bigint): Promise<void>;
    deleteNsoTask(id: bigint): Promise<void>;
    deletePosition(id: bigint): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getAllPositions(): Promise<Array<Position>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoriesByPosition(positionId: bigint): Promise<Array<Category>>;
    getCategory(categoryId: bigint): Promise<Category | null>;
    getItem(itemId: bigint): Promise<LibraryItem | null>;
    getItemsByCategory(categoryId: bigint): Promise<Array<LibraryItem>>;
    getMyAssignments(): Promise<Array<PositionAssignment>>;
    getMyProfile(): Promise<UserProfile | null>;
    getNsoAssignableUsers(): Promise<Array<UserProfile>>;
    getNsoOverallProgress(): Promise<{
        doneCount: bigint;
        totalCount: bigint;
    }>;
    getNsoPhase(id: bigint): Promise<Phase | null>;
    getNsoPhaseProgressCounts(): Promise<Array<NsoPhaseProgressCount>>;
    getNsoPhases(): Promise<Array<Phase>>;
    getNsoTask(id: bigint): Promise<Task | null>;
    getNsoTasksByPhase(phaseId: bigint): Promise<Array<Task>>;
    getPosition(id: bigint): Promise<Position | null>;
    getUserAssignments(userId: Principal): Promise<Array<PositionAssignment>>;
    getUserRole(userId: Principal): Promise<Role | null>;
    importNsoTasks(input: NsoImportInput): Promise<NsoImportSummary>;
    isCallerAdmin(): Promise<boolean>;
    reorderCategories(positionId: bigint, orderedCategoryIds: Array<bigint>): Promise<Array<Category>>;
    reorderItems(categoryId: bigint, orderedItemIds: Array<bigint>): Promise<Array<LibraryItem>>;
    reorderNsoPhases(id: bigint, direction: Variant_up_down): Promise<void>;
    reorderNsoTasks(id: bigint, direction: Variant_up_down): Promise<void>;
    reorderPositions(orderedIds: Array<bigint>): Promise<Array<Position>>;
    schema(): Promise<string>;
    searchLibrary(positionId: bigint, searchText: string): Promise<Array<LibraryItem>>;
    setAssignmentStatus(userId: Principal, positionId: bigint, status: AssignmentStatus): Promise<PositionAssignment>;
    setNsoTaskAssignment(id: bigint, assignedTo: Principal | null): Promise<void>;
    setNsoTaskCompletionDate(id: bigint, completionDate: string | null): Promise<void>;
    setUserRole(userId: Principal, role: Role): Promise<UserProfile>;
    toggleNsoTask(id: bigint, done: boolean, completionDate: string | null): Promise<void>;
    unassignPosition(userId: Principal, positionId: bigint): Promise<void>;
    updateCategory(categoryId: bigint, name: string, coverPhoto: string | null): Promise<Category>;
    updateItem(itemId: bigint, title: string, subtitle: string | null, photo: string | null, details: Array<DetailField>, notes: string | null, tags: Array<string>, seasonal: boolean): Promise<LibraryItem>;
    updateMyProfile(name: string, storeLocation: string): Promise<UserProfile>;
    updateNsoPhase(id: bigint, name: string): Promise<void>;
    updateNsoTask(id: bigint, text: string, section: string | null, done: boolean, assignedTo: Principal | null, completionDate: string | null, notes: string | null): Promise<void>;
    updatePosition(id: bigint, name: string, description: string | null, coverPhoto: string | null): Promise<Position>;
}
import type { AssignmentStatus as _AssignmentStatus, Category as _Category, Cell as _Cell, DetailField as _DetailField, Error as _Error, LibraryItem as _LibraryItem, NsoImportInput as _NsoImportInput, NsoImportPhase as _NsoImportPhase, NsoImportTask as _NsoImportTask, Phase as _Phase, Position as _Position, PositionAssignment as _PositionAssignment, Result as _Result, Result__1 as _Result__1, Role as _Role, Task as _Task, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __assignments(arg0: bigint | null, arg1: bigint | null): Promise<Array<PositionAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.__assignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__assignments(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __categories(arg0: bigint | null, arg1: bigint | null): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.__categories(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__categories(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async __items(arg0: bigint | null, arg1: bigint | null): Promise<Array<LibraryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.__items(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__items(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async __nextCategoryId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextCategoryId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextCategoryId();
            return result;
        }
    }
    async __nextItemId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextItemId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextItemId();
            return result;
        }
    }
    async __nextPhaseId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextPhaseId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextPhaseId();
            return result;
        }
    }
    async __nextPositionId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextPositionId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextPositionId();
            return result;
        }
    }
    async __nextTaskId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextTaskId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextTaskId();
            return result;
        }
    }
    async __nsoPhases(arg0: bigint | null, arg1: bigint | null): Promise<Array<Phase>> {
        if (this.processError) {
            try {
                const result = await this.actor.__nsoPhases(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nsoPhases(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __nsoTasks(arg0: bigint | null, arg1: bigint | null): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.__nsoTasks(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nsoTasks(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async __positions(arg0: bigint | null, arg1: bigint | null): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.__positions(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__positions(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async __profiles(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__profiles(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__profiles(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignPosition(arg0: Principal, arg1: bigint): Promise<PositionAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPosition(arg0, arg1);
                return from_candid_PositionAssignment_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPosition(arg0, arg1);
            return from_candid_PositionAssignment_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCategory(arg0: bigint, arg1: string, arg2: string | null): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Category_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Category_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createItem(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null, arg4: Array<DetailField>, arg5: string | null, arg6: Array<string>, arg7: boolean): Promise<LibraryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createItem(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_LibraryItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItem(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_LibraryItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMyProfile(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createMyProfile(arg0, arg1);
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMyProfile(arg0, arg1);
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNsoPhase(arg0: string): Promise<Phase> {
        if (this.processError) {
            try {
                const result = await this.actor.createNsoPhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNsoPhase(arg0);
            return result;
        }
    }
    async createNsoTask(arg0: bigint, arg1: string, arg2: string | null, arg3: Principal | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createNsoTask(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Task_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNsoTask(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Task_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPosition(arg0: string, arg1: string | null, arg2: string | null): Promise<Position> {
        if (this.processError) {
            try {
                const result = await this.actor.createPosition(arg0, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Position_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPosition(arg0, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Position_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async deleteNsoPhase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNsoPhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNsoPhase(arg0);
            return result;
        }
    }
    async deleteNsoTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNsoTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNsoTask(arg0);
            return result;
        }
    }
    async deletePosition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePosition(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPositions(): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPositions();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPositions();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoriesByPosition(arg0: bigint): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoriesByPosition(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoriesByPosition(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: bigint): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: bigint): Promise<LibraryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByCategory(arg0: bigint): Promise<Array<LibraryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByCategory(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByCategory(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAssignments(): Promise<Array<PositionAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAssignments();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAssignments();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNsoAssignableUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNsoAssignableUsers();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNsoAssignableUsers();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNsoOverallProgress(): Promise<{
        doneCount: bigint;
        totalCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getNsoOverallProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNsoOverallProgress();
            return result;
        }
    }
    async getNsoPhase(arg0: bigint): Promise<Phase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNsoPhase(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNsoPhase(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNsoPhaseProgressCounts(): Promise<Array<NsoPhaseProgressCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNsoPhaseProgressCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNsoPhaseProgressCounts();
            return result;
        }
    }
    async getNsoPhases(): Promise<Array<Phase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNsoPhases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNsoPhases();
            return result;
        }
    }
    async getNsoTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNsoTask(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNsoTask(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNsoTasksByPhase(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNsoTasksByPhase(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNsoTasksByPhase(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosition(arg0: bigint): Promise<Position | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosition(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosition(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAssignments(arg0: Principal): Promise<Array<PositionAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAssignments(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAssignments(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async importNsoTasks(arg0: NsoImportInput): Promise<NsoImportSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.importNsoTasks(to_candid_NsoImportInput_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importNsoTasks(to_candid_NsoImportInput_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reorderCategories(arg0: bigint, arg1: Array<bigint>): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderCategories(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderCategories(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderItems(arg0: bigint, arg1: Array<bigint>): Promise<Array<LibraryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderItems(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderItems(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderNsoPhases(arg0: bigint, arg1: Variant_up_down): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderNsoPhases(arg0, to_candid_variant_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderNsoPhases(arg0, to_candid_variant_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async reorderNsoTasks(arg0: bigint, arg1: Variant_up_down): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderNsoTasks(arg0, to_candid_variant_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderNsoTasks(arg0, to_candid_variant_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async reorderPositions(arg0: Array<bigint>): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderPositions(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderPositions(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchLibrary(arg0: bigint, arg1: string): Promise<Array<LibraryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLibrary(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLibrary(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAssignmentStatus(arg0: Principal, arg1: bigint, arg2: AssignmentStatus): Promise<PositionAssignment> {
        if (this.processError) {
            try {
                const result = await this.actor.setAssignmentStatus(arg0, arg1, to_candid_AssignmentStatus_n69(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PositionAssignment_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAssignmentStatus(arg0, arg1, to_candid_AssignmentStatus_n69(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PositionAssignment_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setNsoTaskAssignment(arg0: bigint, arg1: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNsoTaskAssignment(arg0, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNsoTaskAssignment(arg0, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setNsoTaskCompletionDate(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNsoTaskCompletionDate(arg0, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNsoTaskCompletionDate(arg0, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setUserRole(arg0: Principal, arg1: Role): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n71(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n71(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleNsoTask(arg0: bigint, arg1: boolean, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleNsoTask(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleNsoTask(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async unassignPosition(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unassignPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unassignPosition(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: bigint, arg1: string, arg2: string | null): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Category_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Category_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateItem(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null, arg4: Array<DetailField>, arg5: string | null, arg6: Array<string>, arg7: boolean): Promise<LibraryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_LibraryItem_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_LibraryItem_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1);
                return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1);
            return from_candid_UserProfile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNsoPhase(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNsoPhase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNsoPhase(arg0, arg1);
            return result;
        }
    }
    async updateNsoTask(arg0: bigint, arg1: string, arg2: string | null, arg3: boolean, arg4: Principal | null, arg5: string | null, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNsoTask(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNsoTask(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updatePosition(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null): Promise<Position> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePosition(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Position_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePosition(arg0, arg1, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Position_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AssignmentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentStatus): AssignmentStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_LibraryItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LibraryItem): LibraryItem {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PositionAssignment_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionAssignment): PositionAssignment {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LibraryItem]): LibraryItem | null {
    return value.length === 0 ? null : from_candid_LibraryItem_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Phase]): Phase | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Position]): Position | null {
    return value.length === 0 ? null : from_candid_Position_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categoryId: bigint;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    seasonal: boolean;
    notes: [] | [string];
    details: Array<_DetailField>;
    photo: [] | [string];
    subtitle: [] | [string];
}): {
    id: bigint;
    categoryId: bigint;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    seasonal: boolean;
    notes?: string;
    details: Array<DetailField>;
    photo?: string;
    subtitle?: string;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        title: value.title,
        sortOrder: value.sortOrder,
        tags: value.tags,
        seasonal: value.seasonal,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        details: value.details,
        photo: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.photo)),
        subtitle: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.subtitle))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completionDate: [] | [string];
    assignedTo: [] | [Principal];
    sortOrder: bigint;
    done: boolean;
    text: string;
    section: [] | [string];
    notes: [] | [string];
    phaseId: bigint;
}): {
    id: bigint;
    completionDate?: string;
    assignedTo?: Principal;
    sortOrder: bigint;
    done: boolean;
    text: string;
    section?: string;
    notes?: string;
    phaseId: bigint;
} {
    return {
        id: value.id,
        completionDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.completionDate)),
        assignedTo: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedTo)),
        sortOrder: value.sortOrder,
        done: value.done,
        text: value.text,
        section: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.section)),
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        phaseId: value.phaseId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    sortOrder: bigint;
    name: string;
    description: [] | [string];
    coverPhoto: [] | [string];
}): {
    id: bigint;
    sortOrder: bigint;
    name: string;
    description?: string;
    coverPhoto?: string;
} {
    return {
        id: value.id,
        sortOrder: value.sortOrder,
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.description)),
        coverPhoto: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.coverPhoto))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _Role;
    storeLocation: string;
}): {
    id: Principal;
    name: string;
    role: Role;
    storeLocation: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_Role_n26(_uploadFile, _downloadFile, value.role),
        storeLocation: value.storeLocation
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AssignmentStatus;
    userId: Principal;
    positionId: bigint;
}): {
    status: AssignmentStatus;
    userId: Principal;
    positionId: bigint;
} {
    return {
        status: from_candid_AssignmentStatus_n5(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        positionId: value.positionId
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n44(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n48(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    sortOrder: bigint;
    name: string;
    positionId: bigint;
    coverPhoto: [] | [string];
}): {
    id: bigint;
    sortOrder: bigint;
    name: string;
    positionId: bigint;
    coverPhoto?: string;
} {
    return {
        id: value.id,
        sortOrder: value.sortOrder,
        name: value.name,
        positionId: value.positionId,
        coverPhoto: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.coverPhoto))
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    trainee: null;
} | {
    trainer: null;
}): Role {
    return "manager" in value ? Role.manager : "admin" in value ? Role.admin : "trainee" in value ? Role.trainee : "trainer" in value ? Role.trainer : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n37(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inTraining: null;
} | {
    certified: null;
}): AssignmentStatus {
    return "inTraining" in value ? AssignmentStatus.inTraining : "certified" in value ? AssignmentStatus.certified : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LibraryItem>): Array<LibraryItem> {
    return value.map((x)=>from_candid_LibraryItem_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Position>): Array<Position> {
    return value.map((x)=>from_candid_Position_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PositionAssignment>): Array<PositionAssignment> {
    return value.map((x)=>from_candid_PositionAssignment_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AssignmentStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentStatus): _AssignmentStatus {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_NsoImportInput_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NsoImportInput): _NsoImportInput {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_NsoImportPhase_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NsoImportPhase): _NsoImportPhase {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_NsoImportTask_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NsoImportTask): _NsoImportTask {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n29(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleName: string;
    phases: Array<NsoImportPhase>;
}): {
    moduleName: string;
    phases: Array<_NsoImportPhase>;
} {
    return {
        moduleName: value.moduleName,
        phases: to_candid_vec_n62(_uploadFile, _downloadFile, value.phases)
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<NsoImportTask>;
    name: string;
}): {
    tasks: Array<_NsoImportTask>;
    name: string;
} {
    return {
        tasks: to_candid_vec_n65(_uploadFile, _downloadFile, value.tasks),
        name: value.name
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    section?: string;
    notes?: string;
}): {
    text: string;
    section: [] | [string];
    notes: [] | [string];
} {
    return {
        text: value.text,
        section: value.section ? candid_some(value.section) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_up_down): {
    up: null;
} | {
    down: null;
} {
    return value == Variant_up_down.up ? {
        up: null
    } : value == Variant_up_down.down ? {
        down: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentStatus): {
    inTraining: null;
} | {
    certified: null;
} {
    return value == AssignmentStatus.inTraining ? {
        inTraining: null
    } : value == AssignmentStatus.certified ? {
        certified: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    manager: null;
} | {
    admin: null;
} | {
    trainee: null;
} | {
    trainer: null;
} {
    return value == Role.manager ? {
        manager: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.trainee ? {
        trainee: null
    } : value == Role.trainer ? {
        trainer: null
    } : value;
}
function to_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<NsoImportPhase>): Array<_NsoImportPhase> {
    return value.map((x)=>to_candid_NsoImportPhase_n63(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<NsoImportTask>): Array<_NsoImportTask> {
    return value.map((x)=>to_candid_NsoImportTask_n66(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
